### ISSUE TITLE
MapLoader uses UOFileUop, but why?

### ISSUE THREAD

**Issue by MaxKellermann** [modernuo/ModernUO-Client#13]
https://github.com/modernuo/ModernUO-Client/blob/619ff4a1368bc02eeff23d356578daf3de4a7d99/src/ClassicUO.Assets/MapLoader.cs#L188

This creates a `UOFileUop` instance, but its special features are never used; only the raw file mapping is ever used. How does this make sense? How is this supposed to work, if the UOP variants have a different file format? Can we downgrade this to just `UOFile`?

I don't have UOP data files to test my changes and I don't know a shard which uses UOP files. If you know one, let me know so I can test this.

What's the state of UOP support, anyway? Does anybody use it? Can we drop UOP support? That would allow removing a LOT of code complexity.

**Comment by kamronbatman** [comment]
So the medium/long term plan is to build tooling to convert MUL/UOP to some standardized/simplified file format. For now what people do spans the entire gamut. Some shards want to allow players to use whatever client they want. Newer EA clients don't read the old mul files, while older ones will read them if UOP files are missing.

As for the map UOP format itself, you stumbled upon something that bothers me to no end. The file is sliced into fixed chunks, yet effectively read linearly, ignoring chunk slices. I am not sure what they were thinking when they did this.

I am ok with ditching UOP for MUL (and eventually something else) provided we document a path for converting the files. There is an abandoned project [LegacyMulConverter-N](https://github.com/cbnolok/LegacyMULConverter-N) that could be used as a basis for a new tool.

Should we start a project to convert client files in general? There is quite a bit of streamlining we can do!

**Comment by MaxKellermann** [comment]
I don't care about UOP support, I won't write code to convert those files; all I want is improve the client for Sagas and they don't use UOP. All I care about (regarding this issue) is that my contributions don't break anything for non-Sagas users. If UOP support can be dropped, it would save all of us a lot of brain power, but apparently that's not (yet) the case.

Now about the MapLoader - can you confirm it does work with UOP, or is that unknown, or known-broken? I can't read any sense into that part of the code.

**Comment by kamronbatman** [comment]
I'll test your changes when I get back to the computer and let you know. Before your changes the UOP handling definitely worked for non-sagas users.


I am thinking for now, let's optimize the MUL file handling and leave the UOP shitty until we remove it. Would that work?

**Comment by MaxKellermann** [comment]
> I am thinking for now, let's optimize the MUL file handling and leave the UOP shitty until we remove it. Would that work?

Sure, I wasn't going to optimize that, as it's a dead code path on Sagas. I only touch it to allow the refactoring, because obscure UOP code may prevent code simplifications necessary in other parts of the client; and in MapLoader, the use of class UOFileUop doesn't make sense at all. I just wonder if I'm missing something. But if you don't call any UOFileUop methods, you can just use UOFile, just like I changed many UOFileMul instances to UOFile.

**Comment by MaxKellermann** [comment]
Meanwhile I found out why MapLoader uses UOFileUop; I missed that part:
https://github.com/modernuo/ModernUO-Client/blob/576ee4c644fe5a28aea01d7086495bd4820fd6f5/src/ClassicUO.Assets/MapLoader.cs#L317-L323
