### ISSUE TITLE
What is UltimaLive and do we still need it?

### ISSUE THREAD

**Issue by MaxKellermann** [modernuo/ModernUO-Client#14]
(May I suggest enabling GH Discussions so I can ask questions over there instead of raising an issue?)

I have been preparing a few patches to simplify and optimize the MapLoader, but when I tried to port it from my Sagas branch to this upstream repository, I found lots of API conflicts with the UltimaLive class, which does lots of dirty tricks to mess with the map (the class does not exist in the Sagas branch). It's not a good piece of code.

Googling for UltimaLive, I found https://github.com/praxiiz/UltimaLive - a repository with the most recent commit being 7 years old. This looks like obsolete technology. Just like with UOP, I have no idea if anybody is still using it, but it would simplify my refactoring efforts if this feature could be deleted.

**Comment by kamronbatman** [comment]
No. We do not support Ultima Live. Let's delete it.

**Comment by MaxKellermann** [comment]
OK, I'll send a PR to delete it.

**Comment by kamronbatman** [comment]
I enabled Discussions. I read something about permissions but I don't see a place to change it so let me know if you have issues.
